{% set name = "PartSeg-smfish" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PartSeg-smfish-{{ version }}.tar.gz
  sha256: 658a5dff3fcf24823579e0da8de2e920fd9a03e90b8b703307715185901fbdc0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - partseg >=0.13.0
    - numpy
    - napari
    - qtpy

test:
  imports:
    - PartSeg_smfish
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/4DNucleome/PartSeg-smfish
  summary: PartSeg and napari plugin for smfish data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Czaki
